plugin improvement
aureliencarle/cryptext pull request #35
Opened 2022-04-20 14:27 UTC by aureliencarle

Plugin improvement: 
+ add some cryptext path usefull
+ change the architecture of .cryptewxt directory (with 'core' and 'plugin' directory)
+ plug-in are now local and out of the cryptext core
+ add plugin completion
+ add a plugin list as a session attributs

2022-04-20 18:13 UTC, GregoireUhlrich commented on src/cryptext/commands/imp.py
> +        listing.remove('__pycache__')
Weird to have this here. The list of plugins in session should already take care of this (see below)

2022-04-20 18:13 UTC, GregoireUhlrich commented on src/cryptext/session.py
> +        self.plugins: List[str] = os.listdir(os.path.join(CRYPTPATH, PLUGPATH))
Would put here a condition to extract only plugin python files. By doing so, it is even possible to remove easily the 'plugin_' before and '.py' after:
``` python
import re  # regex python library

def get_valid_plugin(self, file_name: str) -> Optional[str]:
     match = re.match("plugin_(\S+).py", file_name)  # \S+ matches any sequence without space character
     return match.group(1) if match else None  # Return only the plugin name if valid or None
```
It can also be simpler and you can put simply in the init function something like
``` python
self.plugins = [file for file in os.listdir(os.path.join(CRYPTPATH, PLUGPATH)) if file != '__pycache__']
```

PS: The first solution is incomplete, the list of plugins must be then created using the function that returns an optional plugin name if the plugin is valid.

2022-04-21 13:48 UTC, GregoireUhlrich requested changes

2022-04-21 13:48 UTC, GregoireUhlrich commented on src/cryptext/commands/imp.py
> +        listing.remove('__pycache__')
Is this line still useful ?

2022-04-21 13:56 UTC, aureliencarle commented on src/cryptext/commands/imp.py
> +        listing.remove('__pycache__')
No indeed ^^

2022-04-22 07:45 UTC, GregoireUhlrich approved these changes

2022-04-22 07:45 UTC, merged